#pragma config(Sensor, S4,     sonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true)
{int x = SensorValue[sonar];
	displayTextLine(4, "%d", x);
	delay(100);
}
}
