#pragma config(Sensor, S2,     colorSensor,    sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          mediumMotor,   tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{long x;
		long y;
		long z;
		long a;
		long b;
		long c;

	while (true)
	{
	getColorRGB(S2, x, y, z);
	getColorRGB(S3, a, b, c);
	displayTextLine(0, "%d", x);
	displayTextLine(1, "%d", a);
	displayTextLine(3, "%d", y);
	displayTextLine(4, "%d", b);
	displayTextLine(6, "%d", z);
	displayTextLine(7, "%d", c);
	sleep(1000);
	}
}
