#pragma config(Sensor, S2,     colorSensor,    sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          mediumMotor,   tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int x = 0;
	while (x<5)
	{
		setMotorSpeed(motorB, 50);
		setMotorSpeed(motorC, 50);
		delay(5000);
		setMotorSpeed(motorB, 0);
		setMotorSpeed(motorC, 0);
		delay(1000);
		setMotorSpeed(motorA, 50);
		delay(1000);
		setMotorSpeed(motorA, -50);
		delay(1000);
		setMotorSpeed(motorB, 50);
		setMotorSpeed(motorC, 50);
		setMotorSpeed(motorA, 50);
		x++;
		delay(1000);
	}
}
