#pragma config(Sensor, S2,     colorSensor,    sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          mediumMotor,   tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while (true)
	{
		long x;
		long y;
		long z;
		getColorRGB(S2, x, y, z);
		if (x>50)
		{
			setMotorSpeed(motorB, -35);
			setMotorSpeed(motorC, 50);
			delay(10);
			getColorRawRGB(S2, x, y, z);
		}
	else
		{	setMotorSpeed(motorB, 50);
			setMotorSpeed(motorC, -35);
			delay(10);
		}
	}
}
